# Generated by Django 4.2.7 on 2025-07-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_books_available_books_ordered_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='books_available',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
