# Generated by Django 4.2.7 on 2025-07-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_books_ordered_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books_ordered',
            name='image',
        ),
    ]
