# Generated by Django 4.2.7 on 2025-07-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_books_ordered_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='books_ordered',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
